openapi: 3.0.2
info:
  title: Crypto Recommender API
  description: API for aggregating and returning crypto recommendations
  version: 0.1.0
servers:
  - url: /crypto/api/v1
paths:
  /recommendations:
    get:
      summary: List cryptos sorted by normalized range
      operationId: getRecommendations
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 50
        - name: sort_by
          in: query
          required: false
          schema:
            type: string
            enum:
              - normalizedRange_asc
              - normalizedRange_desc
              - symbol_asc
              - symbol_desc
              - min_asc
              - min_desc
              - max_asc
              - max_desc
            default: normalizedRange_desc
          description: Sort field and direction (underscore-separated)
        - name: fromDate
          in: query
          required: false
          schema:
            type: string
            format: date
          description: Start date (inclusive, ISO yyyy-MM-dd)
          example: "2026-01-01"
        - name: toDate
          in: query
          required: false
          schema:
            type: string
            format: date
          description: End date (inclusive, ISO yyyy-MM-dd)
          example: "2026-06-30"
        - name: periodMonths
          in: query
          required: false
          schema:
            type: integer
            enum: [ 1, 3, 6, 12 ]
          description: |
            Predefined period (months lookback from `toDate` or today).
            Mutually exclusive with `fromDate`/`toDate`.
          example: 6
        - name: Authorization
          in: header
          description: Bearer or Token authorization header
          required: true
          schema:
            type: string
      security:
        - TokenAuth: [ ]
      responses:
        '200':
          description: Successful Response
          headers:
            X-RateLimit-Limit:
              description: Max requests per 15 minutes
              schema:
                type: integer
            X-RateLimit-Remaining:
              description: Requests remaining in current window
              schema:
                type: integer
            X-RateLimit-Reset:
              description: Epoch seconds when limit resets
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecommendationsResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Too Many Requests
          headers:
            X-RateLimit-Limit:
              description: Max requests per 15 minutes
              schema:
                type: integer
            X-RateLimit-Remaining:
              description: Requests remaining in current window
              schema:
                type: integer
            X-RateLimit-Reset:
              description: Epoch seconds when limit resets
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /recommendations/{cryptoName}: #todo: path vs query param for crypto name?
    get:
      summary: The statistic details for a requested crypto
      operationId: getRecommendationsByCrypto
      parameters:
        - name: cryptoName #todo: expose list supported cryptos names
          in: path
          description: Name of the crypto to get recommendations for (e.g., BTC, ETH)
          required: true
          schema:
            type: string
        - name: fromDate
          in: query
          required: false
          schema:
            type: string
            format: date
          description: Start date (inclusive, ISO yyyy-MM-dd)
          example: "2026-01-01"
        - name: toDate
          in: query
          required: false
          schema:
            type: string
            format: date
          description: End date (inclusive, ISO yyyy-MM-dd)
          example: "2026-06-30"
        - name: periodMonths
          in: query
          required: false
          schema:
            type: integer
            enum: [ 1, 3, 6, 12 ]
          description: |
            Predefined period (months lookback from `toDate` or today).
            Mutually exclusive with `fromDate`/`toDate`.
          example: 6
        - name: Authorization
          in: header
          description: Bearer or Token authorization header
          required: true
          schema:
            type: string
      security:
        - TokenAuth: [ ]
      responses:
        '200':
          description: Successful Response
          headers:
            X-RateLimit-Limit:
              description: Max requests per 15 minutes
              schema:
                type: integer
            X-RateLimit-Remaining:
              description: Requests remaining in current window
              schema:
                type: integer
            X-RateLimit-Reset:
              description: Epoch seconds when limit resets
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CryptoStats'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found (crypto not found)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Too Many Requests
          headers:
            X-RateLimit-Limit:
              description: Max requests per 15 minutes
              schema:
                type: integer
            X-RateLimit-Remaining:
              description: Requests remaining in current window
              schema:
                type: integer
            X-RateLimit-Reset:
              description: Epoch seconds when limit resets
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /recommendations/top: #todo: make sure no colision with /{cryptoName}
    get:
      summary: The highest normalized range for a specific day or range
      operationId: getRecommendationsTopCrypto
      parameters:
        - name: fromDate
          in: query
          required: false
          schema:
            type: string
            format: date
          description: Start date (inclusive, ISO yyyy-MM-dd)
          example: "2026-01-01"
        - name: toDate
          in: query
          required: false
          schema:
            type: string
            format: date
          description: End date (inclusive, ISO yyyy-MM-dd)
          example: "2026-06-30"
        - name: periodMonths
          in: query
          required: false
          schema:
            type: integer
            enum: [ 1, 3, 6, 12 ]
          description: |
            Predefined period (months lookback from `toDate` or today).
            Mutually exclusive with `fromDate`/`toDate`.
          example: 6
        - name: Authorization
          in: header
          description: Bearer or Token authorization header
          required: true
          schema:
            type: string
      security:
        - TokenAuth: [ ]
      responses:
        '200':
          description: Successful Response
          headers:
            X-RateLimit-Limit:
              description: Max requests per 15 minutes
              schema:
                type: integer
            X-RateLimit-Remaining:
              description: Requests remaining in current window
              schema:
                type: integer
            X-RateLimit-Reset:
              description: Epoch seconds when limit resets
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CryptoStats'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Too Many Requests
          headers:
            X-RateLimit-Limit:
              description: Max requests per 15 minutes
              schema:
                type: integer
            X-RateLimit-Remaining:
              description: Requests remaining in current window
              schema:
                type: integer
            X-RateLimit-Reset:
              description: Epoch seconds when limit resets
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    TokenAuth:
      type: http
      scheme: bearer
      bearerFormat: Token
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        details:
          type: array
          items:
            type: string
    PricePoint:
      type: object
      properties:
        timestamp:
          type: integer
          format: int64
          description: Epoch milliseconds since 1970-01-01
        currency:
          type: string
          example: BTC
        price:
          type: number
          format: double
          example: 12345.67
    CryptoStats: # todo: used as response for single crypto and for list of cryptos?
      type: object # todo: shall be split in two obj ?
      properties: # todo: do we need requsted period in response?
        name:
          type: string
        normalizedRange:
          type: number
          description: (max - min) / min
        oldest:
          $ref: '#/components/schemas/PricePoint'
        newest:
          $ref: '#/components/schemas/PricePoint'
        min:
          $ref: '#/components/schemas/PricePoint'
        max:
          $ref: '#/components/schemas/PricePoint'
    RecommendationsResponse:
      type: object
      properties: # todo: pagination info ? # todo: do we need requsted period in response?
        recommendations:
          type: array
          items:
            $ref: '#/components/schemas/CryptoStats'
        page:
          type: integer
        size:
          type: integer
        totalElements:
          type: integer
        totalPages:
          type: integer


security:
  - TokenAuth: [ ]